export const ENV_GAME_URL = "GAME_URL";
export const ENV_JWT_SECRET = "JWT_SECRET";
export const ENV_CLOUDFLARE_CALLS_URL = "CLOUDFLARE_CALLS_URL";
export const ENV_CLOUDFLARE_CALLS_TOKEN = "CLOUDFLARE_CALLS_TOKEN";
